/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NonLinearRouteImport } from './routes/non-linear'
import { Route as LinearRouteImport } from './routes/linear'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicIdRouteImport } from './routes/topic.$id'

const NonLinearRoute = NonLinearRouteImport.update({
  id: '/non-linear',
  path: '/non-linear',
  getParentRoute: () => rootRouteImport,
} as any)
const LinearRoute = LinearRouteImport.update({
  id: '/linear',
  path: '/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdRoute = TopicIdRouteImport.update({
  id: '/topic/$id',
  path: '/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/linear': typeof LinearRoute
  '/non-linear': typeof NonLinearRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/linear': typeof LinearRoute
  '/non-linear': typeof NonLinearRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/linear': typeof LinearRoute
  '/non-linear': typeof NonLinearRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/linear' | '/non-linear' | '/topic/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/linear' | '/non-linear' | '/topic/$id'
  id: '__root__' | '/' | '/about' | '/linear' | '/non-linear' | '/topic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LinearRoute: typeof LinearRoute
  NonLinearRoute: typeof NonLinearRoute
  TopicIdRoute: typeof TopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/non-linear': {
      id: '/non-linear'
      path: '/non-linear'
      fullPath: '/non-linear'
      preLoaderRoute: typeof NonLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linear': {
      id: '/linear'
      path: '/linear'
      fullPath: '/linear'
      preLoaderRoute: typeof LinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id': {
      id: '/topic/$id'
      path: '/topic/$id'
      fullPath: '/topic/$id'
      preLoaderRoute: typeof TopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LinearRoute: LinearRoute,
  NonLinearRoute: NonLinearRoute,
  TopicIdRoute: TopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
